#!/bin/bash
# This is a config file for Linux Live Kit build script.
# You shouldn't need to change anything expect LIVEKITNAME

# Live Kit Name. Defaults to 'linux';
# This will be the name of the directory created on your CD/USB, which
# will contain everything including boot files and such.
# For example, Slax changes it to 'slax'
# Must not contain any spaces.
# If you change it, you must run ./tools/isolinux.bin.update script
# in order to update isolinux.bin for CD booting.
# If you do not need booting from CD (eg you're booting only from USB)
# then you can ignore recompiling isolinux.bin, just rename LIVEKITNAME
# and you're done.
LIVEKITNAME="slakresq"

# Kernel file, will be copied to your Live Kit
# Your kernel must support aufs and squashfs. Debian Jessie's kernel is ready
# out of the box.
VMLINUZ=/boot/vmlinuz

# Kernel version. Change it to "3.2.28" for example, if you are building
# Live Kit with a different kernel than the one you are actually running
KERNEL=$(uname -r)

# Try to detect it from the installed packages in the target system
KERNEL=`basename /var/log/packages/kernel-generic-* | cut -d - -f 3`

# List of directories for root filesystem
# No subdirectories are allowed, no slashes,
# so You can't use /var/tmp here for example
# Exclude directories like proc sys tmp
MKMOD="bin etc home lib lib64 opt root sbin srv usr var"

# If you require network support in initrd, for example to boot over
# PXE or to load data using 'from' boot parameter from a http server,
# you will need network modules included in your initrd.
# This is disabled by default since most people won't need it.
# To enable, set to true
NETWORK=false

# Try to fsck the source media on boot (and the persistent changes image if
# appropriate). Recommended if you're booting off a USB stick or other writable
# media.
BOOTFSCK=true

# fsck tools to include in the initramfs if BOOTFSCK is enabled. These tools
# must exist in the Linux installation you're building.
FSCKTOOLS="e2fsck fsck.ext2 fsck.ext3 fsck.ext4 fsck.fat fsck.msdos fsck.vfat"

# Enable support to enable persistent storage snapshots. This will add
# mksquashfs to the initramfs
SNAPSHOTS=true

# Temporary directory to store livekit filesystem
LIVEKITDATA=/tmp/$LIVEKITNAME-data-$$

# Bundle extension, for example 'sb' for .sb extension
BEXT=srq

# SquashFS compression options
# The default is XZ compression, which creates tightly-compressed bundles
SQUASHOPTS="-comp xz -b 1024K -Xbcj x86"
# lzo might offer better performance running on older hardware
#SQUASHOPTS="-comp lzo -b 1024K"
# Disable compression entirely. If you only care about speed and not space.
#SQUASHOPTS="-noI -noD -noF -noX"

# Directory with kernel .ko modules, can be different in some distros
LMK="lib/modules/$KERNEL"
